import{S as A,a as b,i as c}from"./assets/vendor-483db976.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function a(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(o){if(o.ep)return;o.ep=!0;const r=a(o);fetch(o.href,r)}})();const C={captionsTitle:"attr",captionsData:"alt"},S=new A(".gallery a",C);function B({webformatURL:e,largeImageURL:t,tags:a,likes:n,views:o,comments:r,downloads:s}){return`<li class="gallery-item">
  <a class="gallery-link" href="${t}">
    <img
      class="gallery-image"
      src="${e}" 
      alt="${a}"
    >
        <div class="all-image-info">
    <p class="image-info"><span class="property-name">Likes</span>${n}</p>
        <p class="image-info"><span class="property-name">Views</span>${o}</p>
            <p class="image-info"><span class="property-name">Comments</span>${r}</p>
                <p class="image-info"><span class="property-name">Downloads</span>${s}</p>
                </div>
    </a>
  </li>`}function w(e){return e.map(B).join("")}function p(e){const t=w(e);document.querySelector(".gallery").insertAdjacentHTML("beforeend",t),S.refresh()}function E(e){if(e===1)return;const t=document.querySelectorAll(".gallery-item"),{height:a}=t[t.length-1].getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}const m=15;async function u(e,t){const o="https://pixabay.com/api/"+"?",r={params:{key:"42187332-ff85343869753156c1a8d7a61",q:`${e}`,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:m}};try{return(await b.get(o,r)).data}catch{throw new Error("Error fetching images from the server")}}const f="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEpSURBVHgBrZXtEcIgDIZTzp5/3URHcSPpJLpBXcVd+FPwiqQt1y+SUNv3DuUkvA+0SQQg5Jx7WOt8zsBYyudEmXsPuijg3bbtB1ipa/jQYQ+UZVmBpHjyprEvyBTGSjf52zwbssdchBxhTkI4c2vtTTJMxcwgw6RObZReXDycMSYBcTWuQX/6RqcMQpCmIOPNHbG30SKAgkjmU8AJBJ3PpQ5GOO2KCYVFGEaFa9J+EbCEDIAsc5SCTCkFPjWXlHWD2Jvw5MNP2b1HBEzN42OZvhMRwmURly1cCvfrszSlC41PxR6SKjQs3g4Qg6z9PpdBxsitIhWDXrPDcZCtWplHHQEhzY+AiOZ7IJz5qg5iWygK/wjfFwD+T18pdfXe37e0j07jTeTBPZYfWztI8097RKsAAAAASUVORK5CYII=";document.addEventListener("submit",L);document.querySelector(".loadBtn").addEventListener("click",P);let i="",l=1,d=!1;function h(){const e=document.getElementById("loader");e.style.display="block"}function g(){const e=document.getElementById("loader");e.style.display="none"}async function L(e){if(e.preventDefault(),l=1,i=e.target.elements.name.value,document.querySelector(".gallery").innerHTML="",document.querySelector(".loadBtn").classList.add("hidden"),i.trim().length===0){c.error({message:"Please enter a valid search term!",position:"topRight",messageColor:"#fafafb",backgroundColor:"#ef4040",iconUrl:f,iconColor:"#ffffff"});return}h();try{const t=await u(i,l);i.length>0&&t.hits.length>0?p(t.hits):c.error({message:"Sorry, there are no images matching<br> your search query. Please try again!",position:"topRight",messageColor:"#fafafb",backgroundColor:"#ef4040",iconUrl:f,iconColor:"#ffffff"}),y(t),g()}catch(t){g(),c.error({message:`${t}`,position:"topRight",messageColor:"#fafafb",backgroundColor:"#ef4040",iconUrl:f,iconColor:"#ffffff"})}e.target.reset()}async function P(){h(),l+=1;try{const e=await u(i,l);p(e.hits),y(e),g()}catch(e){g(),c.error({message:`${e}`,position:"topRight",messageColor:"#fafafb",backgroundColor:"#ef4040",iconUrl:f,iconColor:"#ffffff"})}d&&c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),E()}function y(e){d=Math.ceil(e.totalHits/m)<=l,d?document.querySelector(".loadBtn").classList.add("hidden"):document.querySelector(".loadBtn").classList.remove("hidden")}
//# sourceMappingURL=commonHelpers.js.map
