import{S as A,a as h,i as l}from"./assets/vendor-483db976.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const S={captionsTitle:"attr",captionsData:"alt"},B=new A(".gallery a",S);function b({webformatURL:e,largeImageURL:o,tags:r,likes:n,views:t,comments:s,downloads:a}){return`<li class="gallery-item">
  <a class="gallery-link" href="${o}">
    <img
      class="gallery-image"
      src="${e}" 
      alt="${r}"
    >
        <div class="all-image-info">
    <p class="image-info"><span class="property-name">Likes</span>${n}</p>
        <p class="image-info"><span class="property-name">Views</span>${t}</p>
            <p class="image-info"><span class="property-name">Comments</span>${s}</p>
                <p class="image-info"><span class="property-name">Downloads</span>${a}</p>
                </div>
    </a>
  </li>`}function P(e){return e.map(b).join("")}function g(e){const o=P(e);document.querySelector(".gallery").insertAdjacentHTML("beforeend",o),B.refresh()}function w(e){if(e===1)return;const o=document.querySelectorAll(".gallery-item"),{height:r}=o[o.length-1].getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}const p=15;async function f(e,o){const t="https://pixabay.com/api/"+"?",s={params:{key:"42187332-ff85343869753156c1a8d7a61",q:`${e}`,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:p}};return(await h.get(t,s)).data}const d="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEpSURBVHgBrZXtEcIgDIZTzp5/3URHcSPpJLpBXcVd+FPwiqQt1y+SUNv3DuUkvA+0SQQg5Jx7WOt8zsBYyudEmXsPuijg3bbtB1ipa/jQYQ+UZVmBpHjyprEvyBTGSjf52zwbssdchBxhTkI4c2vtTTJMxcwgw6RObZReXDycMSYBcTWuQX/6RqcMQpCmIOPNHbG30SKAgkjmU8AJBJ3PpQ5GOO2KCYVFGEaFa9J+EbCEDIAsc5SCTCkFPjWXlHWD2Jvw5MNP2b1HBEzN42OZvhMRwmURly1cCvfrszSlC41PxR6SKjQs3g4Qg6z9PpdBxsitIhWDXrPDcZCtWplHHQEhzY+AiOZ7IJz5qg5iWygK/wjfFwD+T18pdfXe37e0j07jTeTBPZYfWztI8097RKsAAAAASUVORK5CYII=";document.addEventListener("submit",C);document.querySelector(".loadBtn").addEventListener("click",L);let i="",c=1;function m(){const e=document.getElementById("loader");e.style.display="block"}function u(){const e=document.getElementById("loader");e.style.display="none"}async function C(e){if(e.preventDefault(),c=1,i=e.target.elements.name.value,document.querySelector(".gallery").innerHTML="",i.trim().length===0){l.error({message:"Please enter a valid search term!",position:"topRight",messageColor:"#fafafb",backgroundColor:"#ef4040",iconUrl:d,iconColor:"#ffffff"});return}m();const o=await f(i,c);i.length>0&&o.hits.length>0?g(o.hits):l.error({message:"Sorry, there are no images matching<br> your search query. Please try again!",position:"topRight",messageColor:"#fafafb",backgroundColor:"#ef4040",iconUrl:d,iconColor:"#ffffff"}),y(o),u(),e.target.reset()}async function L(){m(),c+=1;const e=await f(i,c);g(e.hits),y(e),u(),w()}function y(e){Math.ceil(e.totalHits/p)<=p?(document.querySelector(".loadBtn").classList.add("hidden"),l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):document.querySelector(".loadBtn").classList.remove("hidden")}
//# sourceMappingURL=commonHelpers.js.map
